import Footer from "@/module/Footer/Footer";
import Header from "@/module/Header/Header";
import type { Metadata } from "next";
import StyledComponentsRegistry from "@/lib/registry";

import './global.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <main>
          <StyledComponentsRegistry>
            <Header />
            {children}
            <Footer />
          </StyledComponentsRegistry>
        </main>

      </body>
    </html >
  );
}
